/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { ICounter, ICounterInterface } from "../../interfaces/ICounter";

const _abi = [
  {
    inputs: [],
    name: "decrementCount",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "getCount",
    outputs: [
      {
        internalType: "int256",
        name: "count",
        type: "int256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "incrementCount",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "int256",
        name: "count",
        type: "int256",
      },
    ],
    name: "setCount",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ICounter__factory {
  static readonly abi = _abi;
  static createInterface(): ICounterInterface {
    return new Interface(_abi) as ICounterInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): ICounter {
    return new Contract(address, _abi, runner) as unknown as ICounter;
  }
}
